### ISSUE TITLE
Why is this xlf file doesn't work?

### ISSUE THREAD

**Issue by handhikadj** [matecat/xliff-parser#1]
followed the `xliffToArray()` tutorial but returns empty array

xlf file: https://drive.google.com/file/d/1Ijh_yFXD8XeJQjjgHqCIfG2AymxwSZJN/view?usp=sharing

**Comment by mauretto78** [comment]
Hi,

I tested the file and got no errors, maybe you did something wrong.

You should do that:

```php
...
use Matecat\XliffParser\XliffParser;

...

$parsed = (new XliffParser())->xliffToArray(PATH_TO_YOUR_FILE);

```

Did you use the latest release of the parser? Are you sure about your filepath?

**Comment by Ostico** [comment]
Hi @handhikadj ,
it is possible. MateCat is not tested on PHP8.
